### ISSUE TITLE
Add example csv file

### ISSUE THREAD

**Issue by dmenne** [erikpeter/fbroc#2]
Your Shiny application is nice, and I will recommend it to my students who are not R-able.
However, even as a seasoned programmer I had difficulties to understand how columns of the .csv should be formatted.

Please, shorten the description, and add a sample file and a printout of a few lines to the shiny app online.

**Comment by erikpeter** [comment]
Will add a tutorial to shiny version later, thanks. Will close this here since it not strictly a problem with the main R package, with takes vectors as input and is operated from the console.
